production:
  rails:
    secret_token: ''

  airbrake:
    api_key: ''

  facebook:
    app_id: ''
    app_secret: ''

  twitter:
    key: ''
    secret: ''

  platidoma:
    host: ''
    shop_id: 3
    login: ''
    gate_password: ''

  timepad:
    maillist_add_items_url: 'http://timepad.ru/api/maillist_add_items/'
    organization_id: 1
    maillist_id: 1
    api_key: ''

staging:
  rails:
    secret_token: '108dfd2e72d123260bd786d048671ba5b4948f8f4723ffb1cd182e57ac3419097033e24e66e0951ea24ab185dadb57c1f0d956c76af28a1d7a1402d63706fb21'

  airbrake:
    api_key: ''

  twitter:
    key: ''
    secret: ''

  basic_auth:
    username: ''
    password: ''

  facebook:
    app_id: ''
    app_secret: ''

  platidoma:
    host: ''
    shop_id: 7
    login: ''
    gate_password: ''

  timepad:
    maillist_add_items_url: 'http://timepad.ru/api/maillist_add_items/'
    organization_id: 1
    maillist_id: 1
    api_key: ''


development:
  rails:
    secret_token: '108dfd2e72d123260bd786d048671ba5b4948f8f4723ffb1cd182e57ac3419097033e24e66e0951ea24ab185dadb57c1f0d956c76af28a1d7a1402d63706fb21'

  airbrake:
    api_key: ''

  twitter:
    key: ''
    secret: ''

  facebook:
    app_id: ''
    app_secret: ''

  platidoma:
    host: ''
    shop_id: 7
    login: ''
    gate_password: ''

  timepad:
    maillist_add_items_url: 'http://timepad.ru/api/maillist_add_items/'
    organization_id: 1
    maillist_id: 1
    api_key: ''
